module.exports = [
    {
        emailId: "dom@gmail.com",
        password: "1234",
        name: "Dominic",
        address: "1 East Street",
        phoneNumber: "2012949219",
    },
    {
        emailId: "shawn@gmail.com",
        password: "1234",
        name: "Shawn",
        address: "123 Kearny Ave",
        phoneNumber: "2012949102",
    },
    {
        emailId: "john@gmail.com",
        password: "1234",
        name: "John",
        address: "102 Washington Ave",
        phoneNumber: "2049102031",
    },
    {
        emailId: "joe@gmail.com",
        password: "1234",
        name: "Joe",
        address: "9 New York Ave",
        phoneNumber: "2924910201",
    },
    {
        emailId: "alex@gmail.com",
        password: "1234",
        name: "Alex",
        address: "420 Denwer Ave",
        phoneNumber: "2049120310",
    },
    {
        emailId: "molly@gmail.com",
        password: "1234",
        name: "Molly",
        address: "394 Journal Square",
        phoneNumber: "20481920301",
    },
    {
        emailId: "stella@gmail.com",
        password: "1234",
        name: "Stella",
        address: "89 Central Ave",
        phoneNumber: "2940103021",
    },
    {
        emailId: "sonam@gmail.com",
        password: "1234",
        name: "Sonam",
        address: "90 Westside Ave",
        phoneNumber: "2049203021",
    },
    {
        emailId: "micheal@gmail.com",
        password: "1234",
        name: "Micheal",
        address: "90 Office Street",
        phoneNumber: "2049201021",
    },
    {
        emailId: "richard@gmail.com",
        password: "1234",
        name: "Richard",
        address: "90 Silicon Valley",
        phoneNumber: "2048201401",
    }
]